### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by diana134** [saudslm/recharge-api-node#10]
Hey there! Not sure if this is an issue with this package or something deeper, but I'm hoping you might be able to provide some insight 🙏 

I'm making a call to `recharge.customerAddress.create` like so:
```
recharge.customerAddress
      .create(data)
      .then((address) => {
        return address;
      })
      .catch((err) => {
        console.log("err", err);
        return null;
      });
```
where `data` is:
```
const data = {
      first_name: shopifyAddress.first_name,
      last_name: shopifyAddress.last_name,
      address1: shopifyAddress.address1,
      address2: shopifyAddress.address2,
      zip: shopifyAddress.zip,
      city: shopifyAddress.city,
      company: shopifyAddress.company,
      province: shopifyAddress.province,
      country: shopifyAddress.country,
      phone: shopifyAddress.phone,
    };
```
and I'm catching this error
```
GotError: Request path contains unescaped characters
    at get (C:\Users\Diana\Shopistry\paragon\node_modules\got\dist\source\request-as-event-emitter.js:200:27)
    at new ClientRequest (_http_client.js:148:13)
    at Object.request (https.js:314:10)
    at get (C:\Users\Diana\Shopistry\paragon\node_modules\got\dist\source\request-as-event-emitter.js:197:65)
    at async C:\Users\Diana\Shopistry\paragon\node_modules\got\dist\source\request-as-event-emitter.js:264:13
```

I'm using my own plain `fetch` call to get around this for now, which is working. It's weird that this one function throws an error though, all the other ones I'm using work fine 🤷 

Anyway, any insight greatly appreciated!

**Comment by diana134** [comment]
Oh I feel foolish. I was missing the `customerId` parameter 🤦 

`recharge.customerAddress.create(customerId, data)`
